# Generated by Django 4.2.4 on 2023-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_list_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='pages',
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='translator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
